Import("env")
import os

def generate_web_files_cpp(source, target, env):
    """Generate C++ files from data/ directory contents"""
    project_dir = env.get("PROJECT_DIR")
    data_dir = os.path.join(project_dir, "data")
    src_dir = os.path.join(project_dir, "src")
    include_dir = os.path.join(project_dir, "include")

    if not os.path.exists(data_dir):
        print("No data/ directory found, skipping web file generation")
        return

    # Files to convert
    files_to_convert = []
    for filename in os.listdir(data_dir):
        if filename.endswith(('.html', '.css', '.js')):
            files_to_convert.append(filename)

    if not files_to_convert:
        print("No web files found in data/ directory")
        return

    # Generate header file in include/, cpp in src/
    header_path = os.path.join(include_dir, "WebFilesData.h")
    cpp_path = os.path.join(src_dir, "WebFilesData.cpp")

    print(f"Generating WebFilesData.h and WebFilesData.cpp from {len(files_to_convert)} files...")

    # Create header
    with open(header_path, 'w', encoding='utf-8') as h:
        h.write("#pragma once\n\n")
        h.write("#include <Arduino.h>\n\n")
        h.write("// Auto-generated from data/ directory\n")
        h.write("// Do not edit this file directly - edit files in data/ instead\n\n")

        for filename in files_to_convert:
            var_name = filename.replace('.', '_').replace('-', '_').upper()
            h.write(f"extern const char {var_name}[];\n")

        h.write("\n")

    # Create cpp
    with open(cpp_path, 'w', encoding='utf-8') as cpp:
        cpp.write("#include \"WebFilesData.h\"\n\n")
        cpp.write("// Auto-generated from data/ directory\n")
        cpp.write("// Do not edit this file directly - edit files in data/ instead\n\n")

        for filename in files_to_convert:
            file_path = os.path.join(data_dir, filename)
            var_name = filename.replace('.', '_').replace('-', '_').upper()

            with open(file_path, 'r', encoding='utf-8') as f:
                content = f.read()

            cpp.write(f"const char {var_name}[] PROGMEM = R\"====(\n")
            cpp.write(content)
            cpp.write("\n)====\";\n\n")

    print(f"✓ Generated WebFilesData.h and WebFilesData.cpp")

# Run before compiling - execute immediately during build setup
generate_web_files_cpp(None, None, env)
