#pragma once

#include <Arduino.h>

// Auto-generated from data/ directory
// Do not edit this file directly - edit files in data/ instead

extern const char INDEX_HTML[];
extern const char LED_CONFIG_HTML[];
extern const char SCRIPT_JS[];
extern const char STYLE_CSS[];
extern const char THEME_JS[];

