#include "WebFilesData.h"

// Auto-generated from data/ directory
// Do not edit this file directly - edit files in data/ instead

const char INDEX_HTML[] PROGMEM = R"====(
<!DOCTYPE html>
<html>
<head>
    <title>Modular UI</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="style.css">
    <script src="theme.js"></script>
    <script src="script.js"></script>
</head>
<body>
    <header>
        <div class="header-controls">
            <h1>Modular UI</h1>
            <button type="button" class="theme-toggle" onclick="toggleTheme()">
                <i class="fas fa-sun"></i>
            </button>
        </div>
    </header>
    
    <main>
        <section class="control-group">
            <div class="control">
                <h3>Colour</h3>
                <p>Set all LEDs to specified colour, this will stop any animation.</p>
                <div class="color-picker-container">
                    <div class="color-display" id="colour" onclick="toggleColorPicker()"></div>
                    <div class="color-picker" id="colorPicker" style="display: none;">
                        <div class="color-gradient" id="colorGradient"></div>
                        <div class="color-presets">
                            <div class="preset-color" data-color="#ff0000" style="background: #ff0000;"></div>
                            <div class="preset-color" data-color="#00ff00" style="background: #00ff00;"></div>
                            <div class="preset-color" data-color="#0000ff" style="background: #0000ff;"></div>
                            <div class="preset-color" data-color="#ffff00" style="background: #ffff00;"></div>
                            <div class="preset-color" data-color="#ff00ff" style="background: #ff00ff;"></div>
                            <div class="preset-color" data-color="#00ffff" style="background: #00ffff;"></div>
                            <div class="preset-color" data-color="#ffffff" style="background: #ffffff;"></div>
                            <div class="preset-color" data-color="#ff8000" style="background: #ff8000;"></div>
                            <div class="preset-color" data-color="#8000ff" style="background: #8000ff;"></div>
                            <div class="preset-color" data-color="#ff0080" style="background: #ff0080;"></div>
                            <div class="preset-color" data-color="#00ff88" style="background: #00ff88;"></div>
                            <div class="preset-color" data-color="#000000" style="background: #000000;"></div>
                        </div>
                        <input type="text" id="hexInput" placeholder="#ff0000" maxlength="7" class="hex-input">
                    </div>
                </div>
            </div>
            
            <div class="control">
                <h3>White Light</h3>
                <p>Set all LEDs to white, this will stop any animation.</p>
                <button type="button" id="white" onclick="toggleControl(this)">White</button>
            </div>
        </section>
        
        <section class="control-group">
            <div class="control">
                <h3>Volume Metre</h3>
                <p>Set brightness to follow volume.</p>
                <button type="button" id="vu" onclick="toggleControl(this)">VU</button>
            </div>
            
            <div class="control">
                <h3>Animations</h3>
                <p>Pick from a list of animations, select nothing from the list to cancel animations.</p>
                <select id="animation" onchange="animationChange(this)">
                    <option value="-1">Select Animation</option>
                </select>
            </div>
        </section>
        
        <section class="control-group">
            <div class="control">
                <h3>Brightness</h3>
                <p>Set brightness of the LEDs, this will turn off the volume metre.</p>
                <input type="range" min="0" max="255" id="brightness" onchange="changeBrightness(this)">
            </div>
            
            <div class="control">
                <h3>Settings</h3>
                <p>Device configuration and maintenance options.</p>
                <div class="button-group">
                    <a href="/update" class="button">Update</a>
                    <a href="/setup" class="button">WiFi</a>
                    <a href="/led-config" class="button">LEDs</a>
                    <a href="/logs" class="button">Logs</a>
                </div>
            </div>
        </section>
    </main>
</body>
</html>
)====";

const char LED_CONFIG_HTML[] PROGMEM = R"====(
<!DOCTYPE html>
<html>
<head>
    <title>LED Configuration</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="style.css">
    <script src="theme.js"></script>
</head>
<body>
    <header>
        <div class="header-controls">
            <h1>LED Configuration</h1>
            <button type="button" class="theme-toggle" onclick="toggleTheme()">
                <i class="fas fa-sun"></i>
            </button>
        </div>
    </header>

    <main>
        <div class="container">
            <p>Configure your LED strip settings. Changes require a restart.</p>

            <form action="/save-led-config" method="POST">
                <label for="num_strips">Number of LED Strips:</label>
                <input type="number" id="num_strips" name="num_strips" min="1" max="20" placeholder="e.g., 5" required>

                <label for="leds_per_strip">LEDs per Strip:</label>
                <input type="number" id="leds_per_strip" name="leds_per_strip" min="1" max="300" placeholder="e.g., 29" required>

                <p style="color: var(--text-secondary); font-size: 14px; margin-top: 10px;">
                    <strong>Total LEDs:</strong> <span id="totalLeds">0</span>
                </p>

                <button type="submit">Save LED Configuration & Restart</button>
            </form>

            <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid var(--border-primary);">
                <a href="/" style="color: var(--accent-primary); text-decoration: none;">← Back to Main Controls</a>
                <br><br>
                <a href="/setup" style="color: var(--accent-primary); text-decoration: none;">WiFi Settings</a>
            </div>
        </div>
    </main>

    <script>
        function updateTotalLeds() {
            const numStrips = parseInt(document.getElementById('num_strips').value) || 0;
            const ledsPerStrip = parseInt(document.getElementById('leds_per_strip').value) || 0;
            const total = numStrips * ledsPerStrip;
            document.getElementById('totalLeds').textContent = total;
        }

        function loadCurrentConfig() {
            fetch('/get-led-config')
                .then(response => response.json())
                .then(data => {
                    if (data.hasLedSettings) {
                        document.getElementById('num_strips').value = data.numStrips || '';
                        document.getElementById('leds_per_strip').value = data.ledsPerStrip || '';
                        updateTotalLeds();
                    }
                })
                .catch(error => {
                    console.error('Error loading LED config:', error);
                });
        }

        // Load current config when page loads
        document.addEventListener('DOMContentLoaded', function() {
            loadCurrentConfig();
        });

        // Update total LEDs when inputs change
        document.getElementById('num_strips').addEventListener('input', updateTotalLeds);
        document.getElementById('leds_per_strip').addEventListener('input', updateTotalLeds);
    </script>
</body>
</html>

)====";

const char SCRIPT_JS[] PROGMEM = R"====(
const gateway = `ws://${window.location.hostname}/ws`;
let websocket;

document.addEventListener('DOMContentLoaded', function() {
    initWebSocket();
    initColorPicker();
});

function initWebSocket() {
    console.log('Trying to open a WebSocket connection...');
    websocket = new WebSocket(gateway);
    websocket.onopen = onOpen;
    websocket.onclose = onClose;
    websocket.onmessage = onMessage;
}

function onOpen(event) {
    console.log('Connection opened');
    websocket.send(JSON.stringify({ "message": "connect" }));
}

function onClose(event) {
    console.log('Connection closed');
    setTimeout(initWebSocket, 2000);
}

function onMessage(event) {
    const data = JSON.parse(event.data);
    console.log(data);

    // Ignore log messages (handled by /logs page)
    if (data.type === "log") {
        return;
    }

    if (data.message === "states") {
        data.controls.forEach(control => {
            const element = document.getElementById(control.name);
            if (!element) return;

            if (control.state === true) {
                element.classList.add("active");
                if (control.name === "animation" && control.animation !== undefined) {
                    setAnimationSelect(control.animation);
                }
            } else if (control.state === false) {
                element.classList.remove("active");
            } else if (control.name === "colour") {
                updateColorDisplay(control.state);
            } else if (control.name === "brightness") {
                element.value = control.state;
            }
        });
    } else if (data.animations) {
        populateAnimations(data.animations);
    }
}

function populateAnimations(animations) {
    const select = document.getElementById('animation');
    select.innerHTML = '<option value="-1">Select Animation</option>';
    
    animations.forEach(anim => {
        const option = document.createElement('option');
        option.value = anim.value;
        option.textContent = anim.name;
        select.appendChild(option);
    });
}

function setAnimationSelect(animationValue) {
    const select = document.getElementById('animation');
    select.value = animationValue;
    select.classList.add("active");
}

function animationChange(element) {
    const value = parseInt(element.value);
    
    if (value > -1) {
        element.classList.add("active");
        websocket.send(JSON.stringify({
            "message": "animation",
            "value": true,
            "animation": value
        }));
    } else {
        element.classList.remove("active");
        websocket.send(JSON.stringify({
            "message": "animation",
            "value": false
        }));
    }
}

function toggleControl(element) {
    const isActive = element.classList.contains('active');
    websocket.send(JSON.stringify({
        "message": element.id,
        "value": !isActive
    }));
}

function changeBrightness(element) {
    websocket.send(JSON.stringify({
        "message": element.id,
        "value": parseInt(element.value)
    }));
}

let currentColor = '#ff0000';
let colorPickerOpen = false;

function initColorPicker() {
    const colorDisplay = document.getElementById('colour');
    const colorGradient = document.getElementById('colorGradient');
    const presetColors = document.querySelectorAll('.preset-color');
    const hexInput = document.getElementById('hexInput');
    
    colorDisplay.style.backgroundColor = currentColor;
    hexInput.value = currentColor;
    
    colorGradient.addEventListener('click', function(e) {
        // Make sure we're getting the gradient element, not the ::after overlay
        const target = e.currentTarget; // Use currentTarget instead of target
        const rect = target.getBoundingClientRect();
        const x = e.clientX - rect.left;
        const percent = x / rect.width;
        
        // Map to the exact colors and percentages in the CSS gradient
        const gradientStops = [
            { percent: 0.0000, color: '#ff0000' },    // 0% - Red
            { percent: 0.1666, color: '#ff8000' },    // 16.66% - Orange  
            { percent: 0.3333, color: '#ffff00' },    // 33.33% - Yellow
            { percent: 0.5000, color: '#00ff00' },    // 50% - Green
            { percent: 0.6666, color: '#00ffff' },    // 66.66% - Cyan
            { percent: 0.8333, color: '#0000ff' },    // 83.33% - Blue
            { percent: 1.0000, color: '#ff00ff' }     // 100% - Magenta
        ];
        
        // Find the two stops to interpolate between
        let color;
        if (percent <= 0) {
            color = gradientStops[0].color;
        } else if (percent >= 1) {
            color = gradientStops[gradientStops.length - 1].color;
        } else {
            // Find the segment
            let lowerStop = gradientStops[0];
            let upperStop = gradientStops[1];
            
            for (let i = 0; i < gradientStops.length - 1; i++) {
                if (percent >= gradientStops[i].percent && percent <= gradientStops[i + 1].percent) {
                    lowerStop = gradientStops[i];
                    upperStop = gradientStops[i + 1];
                    break;
                }
            }
            
            // Calculate interpolation factor
            const segmentPercent = (percent - lowerStop.percent) / (upperStop.percent - lowerStop.percent);
            color = interpolateColor(lowerStop.color, upperStop.color, segmentPercent);
        }
        
        
        setColor(color);
    });
    
    presetColors.forEach(preset => {
        preset.addEventListener('click', function() {
            setColor(this.dataset.color);
        });
    });
    
    hexInput.addEventListener('input', function() {
        const value = this.value;
        if (isValidHex(value)) {
            setColor(value);
        }
    });
    
    document.addEventListener('click', function(e) {
        if (!e.target.closest('.color-picker-container')) {
            hideColorPicker();
        }
    });
}

function toggleColorPicker() {
    const picker = document.getElementById('colorPicker');
    const colorControl = document.querySelector('.color-picker-container').closest('.control');
    
    if (colorPickerOpen) {
        hideColorPicker();
    } else {
        picker.style.display = 'block';
        colorControl.classList.add('color-picker-active');
        colorPickerOpen = true;
    }
}

function hideColorPicker() {
    const picker = document.getElementById('colorPicker');
    const colorControl = document.querySelector('.color-picker-container').closest('.control');
    
    picker.style.display = 'none';
    colorControl.classList.remove('color-picker-active');
    colorPickerOpen = false;
}

function updateColorDisplay(color) {
    currentColor = color;
    const colorDisplay = document.getElementById('colour');
    const hexInput = document.getElementById('hexInput');
    
    colorDisplay.style.backgroundColor = color;
    hexInput.value = color;
}

function setColor(color) {
    updateColorDisplay(color);
    websocket.send(JSON.stringify({
        "message": "colour",
        "value": color
    }));
}

function interpolateColor(color1, color2, factor) {
    // Convert hex to RGB
    const hex1 = color1.replace('#', '');
    const hex2 = color2.replace('#', '');
    
    const r1 = parseInt(hex1.substr(0, 2), 16);
    const g1 = parseInt(hex1.substr(2, 2), 16);
    const b1 = parseInt(hex1.substr(4, 2), 16);
    
    const r2 = parseInt(hex2.substr(0, 2), 16);
    const g2 = parseInt(hex2.substr(2, 2), 16);
    const b2 = parseInt(hex2.substr(4, 2), 16);
    
    // Interpolate
    const r = Math.round(r1 + (r2 - r1) * factor);
    const g = Math.round(g1 + (g2 - g1) * factor);
    const b = Math.round(b1 + (b2 - b1) * factor);
    
    // Convert back to hex
    return '#' + 
        r.toString(16).padStart(2, '0') + 
        g.toString(16).padStart(2, '0') + 
        b.toString(16).padStart(2, '0');
}

function hslToHex(h, s, l) {
    l /= 100;
    const a = s * Math.min(l, 1 - l) / 100;
    const f = n => {
        const k = (n + h / 30) % 12;
        const color = l - a * Math.max(Math.min(k - 3, 9 - k, 1), -1);
        return Math.round(255 * color).toString(16).padStart(2, '0');
    };
    return `#${f(0)}${f(8)}${f(4)}`;
}

function isValidHex(hex) {
    return /^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/.test(hex);
}

function colourChange(element) {
    websocket.send(JSON.stringify({
        "message": element.id,
        "value": element.value
    }));
}



)====";

const char STYLE_CSS[] PROGMEM = R"====(
/* Main CSS file with light/dark mode support for all pages */

/* Font Awesome import */
@import url('https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css');

/* Base styles */
* {
    box-sizing: border-box;
}

/* Dark theme (default) - Cyan/Teal accent to match LVGL UI */
:root {
    --bg-primary: linear-gradient(135deg, #0a0a0a 0%, #1a1a1a 50%, #0f0f0f 100%);
    --bg-secondary: linear-gradient(145deg, #1e1e1e, #2a2a2a);
    --bg-tertiary: linear-gradient(90deg, #1a1a1a 0%, #2a2a2a 50%, #1a1a1a 100%);
    --bg-card: linear-gradient(145deg, #2a2a2a, #1a1a1a);
    --text-primary: #e0e0e0;
    --text-secondary: #b0b0b0;
    --text-muted: #666;
    --accent-primary: #00D9FF;        /* Cyan - matches UI_COLOR_PRIMARY */
    --accent-secondary: #00B8E6;      /* Darker cyan */
    --border-primary: #444;
    --border-secondary: #333;
    --shadow-primary: rgba(0, 0, 0, 0.4);
    --shadow-secondary: rgba(0, 0, 0, 0.6);
    --shadow-accent: rgba(0, 217, 255, 0.3);  /* Cyan shadow */
    --input-bg: #1a1a1a;
    --button-bg: linear-gradient(145deg, #2a2a2a, #1a1a1a);
    --form-bg: #0a0a0a;
}

/* Light theme */
body.light {
    --bg-primary: linear-gradient(135deg, #f5f5f5 0%, #e0e0e0 50%, #f0f0f0 100%);
    --bg-secondary: linear-gradient(145deg, #ffffff, #f8f8f8);
    --bg-tertiary: linear-gradient(90deg, #f8f8f8 0%, #ffffff 50%, #f8f8f8 100%);
    --bg-card: linear-gradient(145deg, #f0f0f0, #ffffff);
    --text-primary: #333;
    --text-secondary: #555;
    --text-muted: #999;
    --accent-primary: #00D9FF;
    --accent-secondary: #00B8E6;
    --border-primary: #ddd;
    --border-secondary: #eee;
    --shadow-primary: rgba(0, 0, 0, 0.1);
    --shadow-secondary: rgba(0, 0, 0, 0.15);
    --shadow-accent: rgba(0, 217, 255, 0.2);
    --input-bg: #ffffff;
    --button-bg: linear-gradient(145deg, #f0f0f0, #ffffff);
    --form-bg: #ffffff;
}

body {
    font-family: 'SF Pro Display', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
    background: var(--bg-primary);
    color: var(--text-primary);
    margin: 0;
    padding: 0;
    min-height: 100vh;
    overflow-y: auto;
    transition: all 0.3s ease;
}

/* Prevent tiny scrollbars */
html {
    overflow-y: auto;
}

body::-webkit-scrollbar {
    width: 0px;
    background: transparent;
}

@media (max-width: 768px) {
    body {
        background: var(--bg-secondary);
        background-attachment: scroll;
    }
}

/* Theme toggle button */
.theme-toggle {
    background: var(--button-bg);
    border: 2px solid var(--accent-primary);
    border-radius: 50%;
    width: 50px;
    height: 50px;
    font-size: 20px;
    cursor: pointer;
    display: flex;
    align-items: center;
    justify-content: center;
    transition: all 0.3s ease;
    color: var(--accent-primary);
    position: relative;
    z-index: 1000;
}

.theme-toggle:hover {
    background: var(--accent-primary);
    color: var(--form-bg);
    transform: scale(1.1);
    box-shadow: 0 0 20px var(--shadow-accent);
}

/* Header styles */
header {
    background: var(--bg-tertiary);
    border-bottom: 2px solid var(--accent-primary);
    text-align: center;
    padding: 1.5rem;
    box-shadow: 0 4px 20px var(--shadow-accent);
    position: sticky;
    top: 0;
    z-index: 10002;
    backdrop-filter: blur(10px);
}

.header-controls {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 20px;
    max-width: 1400px;
    margin: 0 auto;
}

.header-controls h1 {
    margin: 0;
}

header h1 {
    margin: 0;
    font-size: clamp(1.8rem, 4vw, 2.5rem);
    font-weight: 300;
    letter-spacing: 2px;
    text-transform: uppercase;
    background: linear-gradient(45deg, var(--accent-primary), var(--accent-secondary), #ff0080);
    background-size: 200% 200%;
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-clip: text;
    animation: gradient 3s ease infinite;
}

@keyframes gradient {
    0% { background-position: 0% 50%; }
    50% { background-position: 100% 50%; }
    100% { background-position: 0% 50%; }
}

/* Main content */
main {
    max-width: 1400px;
    margin: 0 auto;
    padding: 2rem;
}

/* Container styles for setup pages */
.container {
    max-width: 600px;
    margin: 0 auto;
    background: var(--bg-secondary);
    border-radius: 16px;
    padding: 30px;
    border: 2px solid var(--accent-primary);
    box-shadow: 0 8px 32px var(--shadow-primary);
}

/* Control groups */
.control-group {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));
    gap: 1.5rem;
    margin-bottom: 2rem;
}

.control {
    background: var(--bg-secondary);
    border: 1px solid var(--border-secondary);
    border-radius: 16px;
    padding: 2rem;
    box-shadow: 
        0 8px 32px var(--shadow-primary),
        inset 0 1px 0 rgba(255, 255, 255, 0.1);
    transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
    position: relative;
    overflow: visible;
}

.control::before {
    content: '';
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    height: 2px;
    background: linear-gradient(90deg, transparent, var(--accent-primary), transparent);
    opacity: 0;
    transition: opacity 0.3s ease;
}

.control:hover {
    transform: translateY(-4px);
    box-shadow: 
        0 12px 40px var(--shadow-secondary),
        0 0 20px var(--shadow-accent),
        inset 0 1px 0 rgba(255, 255, 255, 0.2);
}

.control:hover:not(.color-picker-active) {
    z-index: 10;
}

.control.color-picker-active {
    z-index: 10001;
}

.control:hover::before {
    opacity: 1;
}

/* Typography */
h1, h2, h3 {
    color: var(--accent-primary);
}

.control h3 {
    margin: 0 0 0.75rem 0;
    font-size: 1.2rem;
    font-weight: 500;
    color: var(--accent-primary);
    text-transform: uppercase;
    letter-spacing: 1px;
    border-bottom: 1px solid rgba(0, 217, 255, 0.2);
    padding-bottom: 0.5rem;
}

.control p, p {
    margin-bottom: 1.5rem;
    color: var(--text-secondary);
    line-height: 1.5;
    font-size: 0.9rem;
}

/* Form elements */
label {
    display: block;
    margin: 15px 0 5px 0;
    color: var(--text-secondary);
    font-weight: bold;
}

input, select {
    width: 100%;
    padding: 12px;
    background: var(--input-bg);
    border: 2px solid var(--border-primary);
    border-radius: 8px;
    color: var(--text-primary);
    font-size: 16px;
    box-sizing: border-box;
    transition: all 0.3s ease;
}

input:focus, select:focus {
    border-color: var(--accent-primary);
    outline: none;
    box-shadow: 0 0 10px var(--shadow-accent);
}

/* Buttons */
button {
    background: var(--button-bg);
    color: var(--text-primary);
    border: 2px solid var(--border-primary);
    padding: 0.75rem 1.5rem;
    border-radius: 12px;
    cursor: pointer;
    font-size: 1rem;
    font-weight: 500;
    text-transform: uppercase;
    letter-spacing: 0.5px;
    transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
    position: relative;
    overflow: hidden;
    min-width: 120px;
}

button::before {
    content: '';
    position: absolute;
    top: 50%;
    left: 50%;
    width: 0;
    height: 0;
    background: radial-gradient(circle, var(--shadow-accent) 0%, transparent 70%);
    transition: all 0.3s ease;
    transform: translate(-50%, -50%);
}

button:hover {
    border-color: var(--accent-primary);
    color: var(--accent-primary);
    box-shadow: 0 0 20px var(--shadow-accent);
}

button:hover::before {
    width: 100px;
    height: 100px;
}

button.active {
    background: linear-gradient(145deg, var(--accent-primary), var(--accent-secondary));
    border-color: var(--accent-primary);
    color: var(--form-bg);
    box-shadow: 
        0 0 20px var(--shadow-accent),
        inset 0 1px 0 rgba(255, 255, 255, 0.2);
}

/* Form specific button styles */
button[type="submit"] {
    width: 100%;
    padding: 15px;
    background: linear-gradient(145deg, var(--accent-primary), var(--accent-secondary));
    color: var(--form-bg);
    border: none;
    border-radius: 8px;
    font-size: 18px;
    font-weight: bold;
    margin-top: 20px;
}

body.light button[type="submit"] {
    background: linear-gradient(145deg, var(--accent-primary), var(--accent-secondary));
    color: white;
}

button[type="submit"]:hover {
    background: linear-gradient(145deg, var(--accent-secondary), var(--accent-primary));
    box-shadow: 0 0 20px var(--shadow-accent);
}

/* Factory reset button */
.factory-reset-btn {
    background: linear-gradient(145deg, #cc4444, #aa2222);
    color: #ffffff;
    margin-top: 20px;
    padding: 12px;
    font-size: 14px;
    font-weight: bold;
}

.factory-reset-btn:hover {
    background: linear-gradient(145deg, #aa2222, #cc4444);
    box-shadow: 0 0 10px rgba(204, 68, 68, 0.5);
}

body.light .factory-reset-btn {
    background: linear-gradient(145deg, #ff6b6b, #ee5a52);
    color: white;
}

body.light .factory-reset-btn:hover {
    background: linear-gradient(145deg, #ee5a52, #ff6b6b);
}

/* Select dropdown styling */
select {
    background: var(--button-bg);
    color: var(--text-primary);
    appearance: none;
    -webkit-appearance: none;
    -moz-appearance: none;
    background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' fill='%2300D9FF' viewBox='0 0 16 16'%3e%3cpath d='m7.247 4.86-4.796 5.481c-.566.647-.106 1.659.753 1.659h9.592a1 1 0 0 0 .753-1.659l-4.796-5.48a1 1 0 0 0-1.506 0z'/%3e%3c/svg%3e");
    background-repeat: no-repeat;
    background-position: right 0.75rem center;
    background-size: 16px 12px;
    color-scheme: dark;
}

body.light select {
    color-scheme: light;
}

select:hover {
    border-color: var(--accent-primary);
    box-shadow: 0 0 15px var(--shadow-accent);
}

select.active {
    border-color: var(--accent-primary);
    box-shadow: 0 0 20px var(--shadow-accent);
    color: var(--accent-primary);
}

select option {
    background: var(--input-bg);
    color: var(--text-primary);
    padding: 0.5rem;
    border: none;
}

select option:hover,
select option:focus {
    background: var(--bg-secondary);
    color: var(--accent-primary);
}

select option:checked {
    background: var(--accent-primary);
    color: var(--form-bg);
}

/* Range inputs */
input[type="range"] {
    -webkit-appearance: none;
    height: 6px;
    border-radius: 3px;
    background: linear-gradient(90deg, var(--border-secondary), var(--border-primary));
    outline: none;
    margin: 1rem 0;
}

input[type="range"]::-webkit-slider-thumb {
    -webkit-appearance: none;
    appearance: none;
    width: 24px;
    height: 24px;
    border-radius: 50%;
    background: linear-gradient(145deg, var(--accent-primary), var(--accent-secondary));
    cursor: pointer;
    box-shadow: 0 0 10px var(--shadow-accent);
    transition: all 0.3s ease;
}

input[type="range"]::-webkit-slider-thumb:hover {
    transform: scale(1.2);
    box-shadow: 0 0 20px var(--shadow-accent);
}

input[type="range"]::-moz-range-thumb {
    width: 24px;
    height: 24px;
    border-radius: 50%;
    background: linear-gradient(145deg, var(--accent-primary), var(--accent-secondary));
    cursor: pointer;
    border: none;
    box-shadow: 0 0 10px var(--shadow-accent);
}

/* Links */
a {
    color: var(--accent-primary);
    text-decoration: none;
    padding: 0.5rem 1rem;
    border: 2px solid var(--accent-primary);
    border-radius: 8px;
    display: inline-block;
    transition: all 0.3s ease;
    text-transform: uppercase;
    font-weight: 500;
    letter-spacing: 0.5px;
}

a:hover {
    background: var(--accent-primary);
    color: var(--form-bg);
    box-shadow: 0 0 20px var(--shadow-accent);
}

.button-group {
    display: flex;
    gap: 0.75rem;
    flex-wrap: wrap;
}

.button {
    background: var(--button-bg);
    color: var(--text-primary);
    border: 2px solid var(--border-primary);
    padding: 0.75rem 1.5rem;
    border-radius: 12px;
    cursor: pointer;
    font-size: 1rem;
    font-weight: 500;
    text-transform: uppercase;
    letter-spacing: 0.5px;
    transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
    text-decoration: none;
    display: inline-block;
}

.button:hover {
    background: var(--button-bg);  /* Keep same background */
    border-color: var(--accent-primary);
    color: var(--accent-primary);
    box-shadow: 0 0 20px var(--shadow-accent);
    transform: translateY(-2px);  /* Subtle lift effect */
}

.button-group .button {
    flex: 1;
    min-width: 120px;
    text-align: center;
}

/* Color picker styles */
.color-picker-container {
    position: relative;
    z-index: 10000;
}

.color-display {
    width: 80px;
    height: 50px;
    border: 2px solid var(--border-primary);
    border-radius: 12px;
    cursor: pointer;
    background: #ff0000;
    transition: all 0.3s ease;
    position: relative;
    overflow: hidden;
}

.color-display::before {
    content: '';
    position: absolute;
    inset: 0;
    background: linear-gradient(45deg, rgba(0,0,0,0.1) 25%, transparent 25%, transparent 75%, rgba(0,0,0,0.1) 75%),
                linear-gradient(45deg, rgba(0,0,0,0.1) 25%, transparent 25%, transparent 75%, rgba(0,0,0,0.1) 75%);
    background-size: 8px 8px;
    background-position: 0 0, 4px 4px;
    opacity: 0;
    transition: opacity 0.3s ease;
}

.color-display:hover {
    border-color: var(--accent-primary);
    box-shadow: 0 0 15px var(--shadow-accent);
    transform: scale(1.05);
}

.color-display:hover::before {
    opacity: 1;
}

.color-picker {
    position: absolute;
    top: 60px;
    left: 0;
    background: var(--bg-secondary);
    border: 2px solid var(--border-primary);
    border-radius: 16px;
    padding: 1rem;
    box-shadow: 
        0 8px 32px var(--shadow-secondary),
        0 0 20px var(--shadow-accent);
    z-index: 9999;
    min-width: 280px;
    animation: slideDown 0.3s ease;
}

@keyframes slideDown {
    from {
        opacity: 0;
        transform: translateY(-10px);
    }
    to {
        opacity: 1;
        transform: translateY(0);
    }
}

.color-gradient {
    width: 100%;
    height: 120px;
    border-radius: 8px;
    background: linear-gradient(to right, 
        #ff0000 0%, 
        #ff8000 16.66%, 
        #ffff00 33.33%, 
        #00ff00 50%, 
        #00ffff 66.66%, 
        #0000ff 83.33%, 
        #ff00ff 100%
    );
    cursor: pointer;
    margin-bottom: 1rem;
    position: relative;
    overflow: hidden;
}

.color-gradient::after {
    content: '';
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background: linear-gradient(to bottom, transparent 0%, rgba(0,0,0,0.8) 100%);
}

.color-presets {
    display: grid;
    grid-template-columns: repeat(6, 1fr);
    gap: 0.5rem;
    margin-bottom: 1rem;
}

.preset-color {
    width: 30px;
    height: 30px;
    border-radius: 8px;
    cursor: pointer;
    border: 2px solid var(--border-primary);
    transition: all 0.3s ease;
    position: relative;
}

.preset-color:hover {
    border-color: var(--accent-primary);
    transform: scale(1.1);
    box-shadow: 0 0 10px var(--shadow-accent);
}

.preset-color:active {
    transform: scale(0.95);
}

.hex-input {
    width: 100%;
    padding: 0.5rem;
    background: var(--input-bg);
    border: 2px solid var(--border-primary);
    border-radius: 8px;
    color: var(--text-primary);
    font-family: 'Courier New', monospace;
    font-size: 0.9rem;
    text-align: center;
    transition: all 0.3s ease;
}

.hex-input:focus {
    outline: none;
    border-color: var(--accent-primary);
    box-shadow: 0 0 10px var(--shadow-accent);
}

/* Special status and hint styles */
.scanning {
    text-align: center;
    color: var(--accent-primary);
    margin: 20px 0;
}

#password_hint {
    color: var(--text-secondary);
    font-size: 12px;
    margin-top: 5px;
}

body.light #password_hint {
    color: var(--text-muted);
}

/* Status page specific styles */
.status-page {
    text-align: center;
}

.status-page .container {
    max-width: 400px;
    margin: 50px auto;
}

.status-page p {
    font-size: 18px;
}

/* Factory reset specific styling */
.factory-reset-page .container {
    border-color: #cc4444;
}

.factory-reset-page h1 {
    color: #cc4444;
}

body.light .factory-reset-page h1 {
    color: #cc4444;
}

/* Responsive design */
@media (max-width: 768px) {
    main {
        padding: 1rem;
    }
    
    .control-group {
        grid-template-columns: 1fr;
        gap: 1rem;
    }
    
    .control {
        padding: 1.5rem;
    }
    
    header {
        padding: 1rem;
    }
    
    .header-controls {
        flex-direction: column;
        gap: 1rem;
    }
    
    button {
        width: 100%;
        margin: 0.25rem 0;
    }
    
    .container {
        margin: 1rem;
        padding: 20px;
    }
}

@media (max-width: 480px) {
    .control {
        padding: 1rem;
    }
    
    .control h3 {
        font-size: 1rem;
    }
    
    button {
        padding: 0.5rem 1rem;
        font-size: 0.9rem;
    }
    
    .container {
        margin: 0.5rem;
        padding: 15px;
    }
}
)====";

const char THEME_JS[] PROGMEM = R"====(
// Theme management JavaScript for all pages

function toggleTheme() {
    const body = document.body;
    const themeToggle = document.querySelector('.theme-toggle');
    
    body.classList.toggle('light');
    
    if (body.classList.contains('light')) {
        themeToggle.innerHTML = '<i class="fas fa-moon"></i>';
        localStorage.setItem('theme', 'light');
    } else {
        themeToggle.innerHTML = '<i class="fas fa-sun"></i>';
        localStorage.setItem('theme', 'dark');
    }
}

// Load saved theme on page load
function loadTheme() {
    const savedTheme = localStorage.getItem('theme');
    const body = document.body;
    const themeToggle = document.querySelector('.theme-toggle');
    
    if (savedTheme === 'light') {
        body.classList.add('light');
        if (themeToggle) {
            themeToggle.innerHTML = '<i class="fas fa-moon"></i>';
        }
    } else {
        if (themeToggle) {
            themeToggle.innerHTML = '<i class="fas fa-sun"></i>';
        }
    }
}

// Initialize theme on DOM content loaded
document.addEventListener('DOMContentLoaded', function() {
    loadTheme();
});
)====";

